version: '3.8'

services:
  boomit-api:
    build:
      context: .
      dockerfile: deployments/docker/dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
